# Generated by Django 2.2.7 on 2019-11-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=300)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
