# Generated by Django 2.2.7 on 2019-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='type',
            field=models.CharField(default='Member', max_length=10),
        ),
    ]
