# Generated by Django 2.2.7 on 2019-12-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
