# Generated by Django 2.2.7 on 2019-12-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0002_userproject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
