# Generated by Django 2.2.7 on 2019-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0003_auto_20191216_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(null=True),
        ),
    ]
