# Generated by Django 2.2.7 on 2019-12-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0003_user_random_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
