# Generated by Django 2.2.7 on 2019-12-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0005_project_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('change', models.CharField(default='rm', max_length=2)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_admin', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SUSTex.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('authority', models.CharField(default='rw', max_length=2)),
                ('accept', models.CharField(default='wait', max_length=6)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='I_admin', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SUSTex.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='I_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
