# Generated by Django 2.2.7 on 2019-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0005_auto_20191216_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
