# Generated by Django 2.2.7 on 2019-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0006_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='random_str',
            field=models.CharField(default='####################', max_length=30),
        ),
    ]
