# Generated by Django 2.2.7 on 2019-12-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0007_auto_20191217_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='filename',
        ),
    ]
