# Generated by Django 2.2.7 on 2019-12-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0007_auto_20191225_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUSTex.Project', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
