# Generated by Django 2.2.7 on 2019-12-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0008_auto_20191217_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='userproject',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='userproject',
            old_name='user_id',
            new_name='user',
        ),
    ]
