# Generated by Django 2.2.7 on 2019-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0008_auto_20191227_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='main.tex', max_length=50),
        ),
    ]
