# Generated by Django 2.2.7 on 2019-12-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0009_auto_20191217_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='random_str',
            field=models.CharField(default='####################', max_length=30, unique=True),
        ),
    ]
