# Generated by Django 2.2.7 on 2019-12-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0010_auto_20191217_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('project', 'user')},
        ),
    ]
