# Generated by Django 2.2.7 on 2019-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0014_auto_20191217_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
