# Generated by Django 2.2.7 on 2019-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0015_auto_20191217_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='authority',
            field=models.CharField(default='rw', max_length=2),
        ),
    ]
