# Generated by Django 2.2.7 on 2019-12-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0018_project_last_modify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date',
            new_name='last_modify',
        ),
    ]
