# Generated by Django 2.2.7 on 2019-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0021_auto_20191219_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
