# Generated by Django 2.2.7 on 2019-12-21 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0022_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_index=True, default=0)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent_version', models.IntegerField(default=0)),
                ('data', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUSTex.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'version'), ('document', 'user', 'parent_version')},
            },
        ),
    ]
