# Generated by Django 2.2.7 on 2019-12-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUSTex', '0024_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
